process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./redux/ReduxProvider";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <div className="header-css">
            <Header />
          </div>
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
